const translations = {
  en: {
    status_badge: "GHOST-MODE ACTIVE",
    hero_title_a: "Untraceable.",
    hero_title_b: "Weapon-Grade Privacy.",
    subtitle_a: "RoomOff is a pure WebRTC peer-to-peer environment. Your conversations, audio, and video never touch our servers. They exist only in the ephemeral memory of the devices involved.",
    subtitle_b: "Unlike traditional messaging apps that install vulnerabilities on your device, RoomOff leaves no footprint. No downloaded executable means no malware target.",
    subtitle_c: "Because privacy should never require a subscription, a phone number, or an email address.",
    cta_button: "Enter a Secure Room (mYRC v2.6.0-beta)",
    cta_note: "100% Free. No account required. Instant anonymous access.",
    metric_no_account_value: "Zero Accounts",
    metric_no_account_label: "No email, no phone number, no identity",
    metric_no_payment_value: "100% Free",
    metric_no_payment_label: "No subscriptions, no premium tiers, no ads",
    metric_no_storage_value: "Zero Storage",
    metric_no_storage_label: "No cloud database, no server-side history",
    metric_no_download_value: "No Installation",
    metric_no_download_label: "Browser-native, zero attack surface on disk",    
    metric_peers_value: "Up to 5 peers",
    metric_peers_label: "Small-room WebRTC mesh",
    metric_media_value: "Text + audio + video",
    metric_media_label: "Rich chat, camera and screen sharing",
    metric_privacy_value: "No chat history",
    features_title: "Built for a world where your device might already be compromised.",
    features_desc: "RoomOff adds application-layer text encryption on top of browser WebRTC transport, uses volatile room keys, and clearly marks which protections are browser-enforced and which are best-effort interface defenses.",
    card_ratchet_title: "Evolving Encryption Keys",
    card_ratchet_desc: "Text messages use volatile room keys, ephemeral peer handshakes and per-message ratcheting before they enter the WebRTC data channel. Browser media remains protected by WebRTC DTLS/SRTP.",
    card_ram_title: "RAM Zeroization",
    card_ram_desc: "RoomOff avoids key persistence, zeroizes byte buffers it controls, and minimizes how long sensitive text stays rendered. Browser internals may still keep temporary copies outside app control.",
    card_anti_capture_title: "Anti-Screen Capture",
    card_anti_capture_desc: "Highly sensitive messages can be configured to only reveal themselves under active, continuous user pressure. Release the button, and the text vanishes instantly from screen and memory.",
    card_immunity_title: "Environment Immunity",
    card_immunity_desc: "RoomOff adds best-effort warnings for screen sharing and suspicious debugging pauses. Browsers cannot reliably identify every recorder or remote access tool.",
    card_p2p_title: "Pure Peer-to-Peer",
    card_p2p_desc: "Our relay does nothing but introduce browsers. Once connected, text, audio, and video flow directly between devices via encrypted WebRTC, bypassing any central server completely.",
    card_room_title: "Self-Destructing Rooms",
    card_room_desc: "A URL creates an isolated environment. When the last person leaves, the room is purged from the temporary relay file. It is as if the conversation never existed.",
    card_identity_title: "No Identity Layer",
    card_identity_desc: "No registration, no usernames, no persistent identifiers.",
    card_ephemeral_title: "Ephemeral Rooms",
    card_ephemeral_desc: "Rooms are temporary coordination spaces that can disappear when peers leave.",
    privacy_eyebrow: "Radical Transparency",
    privacy_title: "See exactly what is hidden, and from whom.",
    privacy_desc: "We don't ask you to trust us blindly. RoomOff provides an in-room transparency panel that separates what the minimal relay sees from what travels directly and secretly between you and your peers.",
    privacy_server_title: "Relay-visible data",
    privacy_server_desc: "Temporary room state, anonymous peer IDs, and WebRTC handshake packets. Nothing more.",
    privacy_peer_title: "Peer-carried data",
    privacy_peer_desc: "Text, media, audio, and video encrypted end-to-end via WebRTC data channels.",
    privacy_history_title: "No archive, ever",
    privacy_history_desc: "The relay is stateless regarding content. Empty rooms are immediately wiped from memory.",
    docs_eyebrow: "How it works",
    docs_title: "The lifecycle of an untraceable room.",
    docs_desc: "A precise overview for users, partners, and reviewers who want to understand the technical flow without the marketing fluff.",
    doc_start_title: "1. Generate a Ghost Room",
    doc_start_desc: "A room name creates a temporary, volatile coordination space. No identity binding or account creation occurs.",
    doc_signal_title: "2. Secure Signaling",
    doc_signal_desc: "The relay routes encrypted WebRTC offers, answers, and ICE candidates strictly to intended peers.",
    doc_chat_title: "3. Direct Mesh Exchange",
    doc_chat_desc: "Messages and rich formatting are sent through peer-to-peer data channels, completely bypassing the relay infrastructure.",
    doc_media_title: "4. On-Demand Media",
    doc_media_desc: "Camera, microphone, and screen sharing are optional and renegotiated dynamically across the encrypted mesh.",
    doc_limit_title: "5. Intentional Scaling Limits",
    doc_limit_desc: "Rooms are capped at five peers to guarantee a stable, high-bandwidth mesh network across all mobile and desktop devices.",
    doc_panel_title: "6. Audit Your Session",
    doc_panel_desc: "The transparency panel logs the exact technical state of your connections, giving you total control over your privacy audit.",
    doc_commands_title: "7. Use mYRC Commands",
    doc_commands_desc: "Control rooms with classic chat commands for nicknames, topics, actions, notices, microphone controls and sensitive messages.",
    doc_commands_link: "Read commands",
    compat_eyebrow: "Compatibility",
    compat_title: "Native browser security on any device.",
    compat_desc: "Because RoomOff refuses to be a downloadable application, it relies on the hardened sandbox environments of modern browsers. No local binaries to exploit.",
    faq_eyebrow: "FAQ",
    faq_title: "Questions people ask before entering a secure room.",
    faq_store_q: "If I don't create an account, how do you stop abuse?",
    faq_store_a: "Rooms are ephemeral and strictly limited in size. Without persistent identities or stored data, there is no target for attackers. Abuse requires a footprint; RoomOff has none.",
    faq_video_q: "Can screen recorders or spyware on my PC read my messages?",
    faq_video_a: "RoomOff can mask sensitive messages, warn before screen sharing, avoid key persistence, and zeroize byte buffers it controls. No browser app can guarantee protection from malware or a recorder already running on your device.",
    faq_limit_q: "Why limit rooms to five peers if it's peer-to-peer?",
    faq_limit_a: "A WebRTC mesh network means every user connects directly to every other user. Capping at five ensures the encryption and media routing remain flawless and fast, without requiring centralized servers that would compromise privacy.",
    faq_server_q: "What exactly does the minimal relay see?",
    faq_server_a: "It sees temporary room coordinates and anonymous WebRTC handshake packets. It acts as a blind postman. It cannot read the messages, see the video, or decrypt the audio passing between peers.",
    faq_mobile_q: "Is it truly free with no hidden premium tiers?",
    faq_mobile_a: "Yes. Privacy is a fundamental right, not a premium feature to be monetized. There are no accounts to upsell, no cloud storage costs to pass on, and no advertisements tracking your behavior.",
    footer_prefix: "RoomOff. Private rooms that exist only while people use them.",
    footer_contact: "Contact Us",
    footer_partners: "Partners & Invited Guests"
  },
  fr: {
    status_badge: "MODE FANTÔME ACTIF",
    hero_title_a: "Intraçable.",
    hero_title_b: "Confidentialité de niveau militaire.",
    subtitle_a: "RoomOff est un environnement pair-à-pair WebRTC pur. Vos conversations, audio et vidéo ne touchent jamais nos serveurs. Ils n'existent que dans la mémoire éphémère des appareils impliqués.",
    subtitle_b: "Contrairement aux applications de messagerie traditionnelles qui installent des vulnérabilités sur votre appareil, RoomOff ne laisse aucune trace. Aucun exécutable téléchargé signifie aucune cible pour les malwares.",
    subtitle_c: "Parce que la confidentialité ne devrait jamais exiger un abonnement, un numéro de téléphone ou une adresse e-mail.",
    cta_button: "Entrer dans une salle sécurisée (mYRC v2.6.0-beta)",
    cta_note: "100% Gratuit. Aucun compte requis. Accès anonyme instantané.",
    metric_no_account_value: "Zéro Compte",
    metric_no_account_label: "Pas d'e-mail, pas de téléphone, pas d'identité",
    metric_no_payment_value: "100% Gratuit",
    metric_no_payment_label: "Pas d'abonnements, pas de versions premium, pas de pubs",
    metric_no_storage_value: "Zéro Stockage",
    metric_no_storage_label: "Pas de base de données cloud, pas d'historique serveur",
    metric_no_download_value: "Aucune Installation",
    metric_no_download_label: "Natif navigateur, surface d'attaque nulle sur le disque",
    metric_peers_value: "Jusqu'a 5 pairs",
    metric_peers_label: "Maillage WebRTC pour petites salles",
    metric_media_value: "Texte + audio + vidéo",
    metric_media_label: "Clavardage riche, caméra et partage d'écran",
    features_eyebrow: "Architecture de sécurité de nouvelle génération",
    features_title: "Conçu pour un monde où votre appareil est peut-être déjà compromis.",
    features_desc: "RoomOff adds application-layer text encryption on top of browser WebRTC transport, uses volatile room keys, and clearly marks which protections are browser-enforced and which are best-effort interface defenses.",
    card_ratchet_title: "Clés de chiffrement évolutives",
    card_ratchet_desc: "Text messages use volatile room keys, ephemeral peer handshakes and per-message ratcheting before they enter the WebRTC data channel. Browser media remains protected by WebRTC DTLS/SRTP.",
    card_ram_title: "Effacement de la RAM (Zeroization)",
    card_ram_desc: "RoomOff avoids key persistence, zeroizes byte buffers it controls, and minimizes how long sensitive text stays rendered. Browser internals may still keep temporary copies outside app control.",
    card_anti_capture_title: "Anti-capture d'écran",
    card_anti_capture_desc: "Les messages très sensibles peuvent être configurés pour ne se révéler que sous une pression continue de l'utilisateur. Relâchez le bouton, et le texte disparaît instantanément de l'écran et de la mémoire.",
    card_immunity_title: "Immunité environnementale",
    card_immunity_desc: "RoomOff adds best-effort warnings for screen sharing and suspicious debugging pauses. Browsers cannot reliably identify every recorder or remote access tool.",
    card_p2p_title: "Pur pair-à-pair",
    card_p2p_desc: "Notre relais ne fait que présenter les navigateurs. Une fois connectés, texte, audio et vidéo circulent directement entre les appareils via WebRTC chiffré, contournant totalement tout serveur central.",
    card_room_title: "Salles autodestructrices",
    card_room_desc: "Une URL crée un environnement isolé. Quand le dernier partant quitte, la salle est purgée du fichier relais temporaire. C'est comme si la conversation n'avait jamais existé.",
    card_identity_title: "Aucune couche d'identité",
    card_identity_desc: "Aucune inscription, aucun nom d'utilisateur, aucun identifiant persistant.",
    card_ephemeral_title: "Salles éphémères",
    card_ephemeral_desc: "Les salles sont des espaces temporaires de coordination qui peuvent disparaître quand les pairs quittent.",
    privacy_eyebrow: "Transparence radicale",
    privacy_title: "Voyez exactement ce qui est caché, et à qui.",
    privacy_desc: "Nous ne vous demandons pas de nous faire aveuglément confiance. RoomOff fournit un panneau de transparence dans la salle qui sépare ce que le relais minimal voit de ce qui voyage secrètement entre vous et vos pairs.",
    privacy_server_title: "Données visibles par le relais",
    privacy_server_desc: "L'état temporaire de la salle, les IDs de pairs anonymes et les paquets de poignée de main WebRTC. Rien de plus.",
    privacy_peer_title: "Données transportées par les pairs",
    privacy_peer_desc: "Texte, médias, audio et vidéo chiffrés de bout en bout via les canaux de données WebRTC.",
    privacy_history_title: "Aucune archive, jamais",
    privacy_history_desc: "Le relais est sans état concernant le contenu. Les salles vides sont immédiatement effacées de la mémoire.",
    docs_eyebrow: "Comment ça marche",
    docs_title: "Le cycle de vie d'une salle intraçable.",
    docs_desc: "Un aperçu précis pour les utilisateurs, partenaires et réviseurs qui veulent comprendre le flux technique sans le battage marketing.",
    doc_start_title: "1. Générer une salle fantôme",
    doc_start_desc: "Un nom de salle crée un espace de coordination temporaire et volatil. Aucune liaison d'identité ou création de compte ne se produit.",
    doc_signal_title: "2. Signalisation sécurisée",
    doc_signal_desc: "Le relais achemine les offres, réponses et candidats ICE WebRTC chiffrés strictement aux pairs visés.",
    doc_chat_title: "3. Échange maillé direct",
    doc_chat_desc: "Les messages et le formatage riche sont envoyés via des canaux de données pair-à-pair, contournant totalement l'infrastructure du relais.",
    doc_media_title: "4. Médias à la demande",
    doc_media_desc: "Caméra, micro et partage d'écran sont optionnels et renégociés dynamiquement à travers le maillage chiffré.",
    doc_limit_title: "5. Limites d'échelle intentionnelles",
    doc_limit_desc: "Les salles sont plafonnées à cinq pairs pour garantir un réseau maillé stable et à haut débit sur tous les appareils mobiles et de bureau.",
    doc_panel_title: "6. Auditer votre session",
    doc_panel_desc: "Le panneau de transparence enregistre l'état technique exact de vos connexions, vous donnant un contrôle total sur votre audit de confidentialité.",
    compat_eyebrow: "Compatibilité",
    compat_title: "Sécurité native du navigateur sur n'importe quel appareil.",
    compat_desc: "Parce que RoomOff refuse d'être une application téléchargeable, il s'appuie sur les environnements sandbox renforcés des navigateurs modernes. Aucun binaire local à exploiter.",
    faq_eyebrow: "FAQ",
    faq_title: "Questions que les gens posent avant d'entrer dans une salle sécurisée.",
    faq_store_q: "Si je ne crée pas de compte, comment empêchez-vous les abus ?",
    faq_store_a: "Les salles sont éphémères et strictement limitées en taille. Sans identités persistantes ou données stockées, il n'y a pas de cible pour les attaquants. L'abus nécessite une empreinte ; RoomOff n'en a pas.",
    faq_video_q: "Les enregistreurs d'écran ou les spywares sur mon PC peuvent-ils lire mes messages ?",
    faq_video_a: "RoomOff can mask sensitive messages, warn before screen sharing, avoid key persistence, and zeroize byte buffers it controls. No browser app can guarantee protection from malware or a recorder already running on your device.",
    faq_limit_q: "Pourquoi limiter les salles à cinq pairs si c'est du pair-à-pair ?",
    faq_limit_a: "Un réseau maillé WebRTC signifie que chaque utilisateur se connecte directement à chaque autre utilisateur. Limiter à cinq garantit que le chiffrement et le routage média restent parfaits et rapides.",
    faq_server_q: "Que voit exactement le relais minimal ?",
    faq_server_a: "Il voit les coordonnées temporaires de la salle et les paquets de poignée de main WebRTC anonymes. Il agit comme un facteur aveugle. Il ne peut pas lire les messages, voir la vidéo ou déchiffrer l'audio.",
    faq_mobile_q: "Est-ce vraiment gratuit sans cachettes payantes ?",
    faq_mobile_a: "Oui. La vie privée est un droit fondamental, pas une fonctionnalité premium à monétiser. Il n'y a pas de comptes à vendre, pas de coûts de stockage cloud à répercuter, et pas de publicités qui vous traquent.",
    footer_prefix: "RoomOff. Des salles privées qui existent seulement pendant leur utilisation.",
    footer_contact: "Nous contacter",
    footer_partners: "Partenaires et invités"
  },
  es: {
    status_badge: "MODO FANTASMA ACTIVO",
    hero_title_a: "Inrastreable.",
    hero_title_b: "Privacidad de nivel militar.",
    subtitle_a: "RoomOff es un entorno WebRTC puro de igual a igual. Tus conversaciones, audio y video nunca pasan por nuestros servidores. Existen únicamente en la memoria efímera de los dispositivos involucrados.",
    subtitle_b: "A diferencia de las aplicaciones de mensajería tradicionales que instalan vulnerabilidades en tu dispositivo, RoomOff no deja ningún rastro. Al no haber ejecutables descargables, no existe un objetivo para el malware.",
    subtitle_c: "Porque la privacidad nunca debería requerir una suscripción, un número de teléfono o una dirección de correo electrónico.",
    cta_button: "Entrar en una Sala Segura (mYRC v2.6.0-beta)",
    cta_note: "100% Gratis. No se requiere cuenta. Acceso anónimo instantáneo.",
    metric_no_account_value: "Cero Cuentas",
    metric_no_account_label: "Sin correo electrónico, sin número de teléfono, sin identidad",
    metric_no_payment_value: "100% Gratis",
    metric_no_payment_label: "Sin suscripciones, sin funciones premium, sin anuncios",
    metric_no_storage_value: "Cero Almacenamiento",
    metric_no_storage_label: "Sin base de datos en la nube, sin historial en el servidor",
    metric_no_download_value: "Sin Instalación",
    metric_no_download_label: "Nativo del navegador, superficie de ataque cero en el disco",
    metric_peers_value: "Hasta 5 pares",
    metric_peers_label: "Malla WebRTC para salas pequeñas",
    metric_media_value: "Texto + audio + video",
    metric_media_label: "Chat enriquecido, cámara y pantalla",
    features_eyebrow: "Arquitectura de Seguridad de Nueva Generación",
    features_title: "Diseñado para un mundo donde tu dispositivo podría estar ya comprometido.",
    features_desc: "RoomOff adds application-layer text encryption on top of browser WebRTC transport, uses volatile room keys, and clearly marks which protections are browser-enforced and which are best-effort interface defenses.",
    card_ratchet_title: "Claves de Cifrado Evolutivas",
    card_ratchet_desc: "Text messages use volatile room keys, ephemeral peer handshakes and per-message ratcheting before they enter the WebRTC data channel. Browser media remains protected by WebRTC DTLS/SRTP.",
    card_ram_title: "Borrado Seguro de RAM",
    card_ram_desc: "RoomOff avoids key persistence, zeroizes byte buffers it controls, and minimizes how long sensitive text stays rendered. Browser internals may still keep temporary copies outside app control.",
    card_anti_capture_title: "Protección contra Capturas de Pantalla",
    card_anti_capture_desc: "Los mensajes altamente sensibles pueden configurarse para revelarse únicamente mientras el usuario mantenga una presión continua. Al soltar el botón, el texto desaparece instantáneamente de la pantalla y de la memoria.",
    card_immunity_title: "Inmunidad del Entorno",
    card_immunity_desc: "RoomOff adds best-effort warnings for screen sharing and suspicious debugging pauses. Browsers cannot reliably identify every recorder or remote access tool.",
    card_p2p_title: "Puro Peer-to-Peer",
    card_p2p_desc: "Nuestro servidor de retransmisión solo presenta los navegadores entre sí. Una vez conectados, el texto, el audio y el video fluyen directamente entre los dispositivos mediante WebRTC cifrado, evitando por completo cualquier servidor central.",
    card_room_title: "Salas Autodestructivas",
    card_room_desc: "Una URL crea un entorno aislado. Cuando la última persona abandona la sala, esta se elimina del archivo temporal del servidor de retransmisión. Es como si la conversación nunca hubiera existido.",
    card_identity_title: "Sin capa de identidad",
    card_identity_desc: "Sin registro, sin nombres de usuario, sin identificadores persistentes.",
    card_ephemeral_title: "Salas efímeras",
    card_ephemeral_desc: "Las salas son espacios temporales de coordinación que pueden desaparecer cuando los pares salen.",
    privacy_eyebrow: "Transparencia Radical",
    privacy_title: "Descubre exactamente qué permanece oculto y para quién.",
    privacy_desc: "No te pedimos que confíes en nosotros a ciegas. RoomOff ofrece un panel de transparencia dentro de la sala que separa lo que ve el servidor mínimo de retransmisión de lo que viaja directamente y en secreto entre tú y tus pares.",
    privacy_server_title: "Datos visibles para el servidor",
    privacy_server_desc: "Estado temporal de la sala, identificadores anónimos de los pares y paquetes de negociación WebRTC. Nada más.",
    privacy_peer_title: "Datos transportados entre pares",
    privacy_peer_desc: "Texto, contenido multimedia, audio y video cifrados de extremo a extremo mediante canales de datos WebRTC.",
    privacy_history_title: "Sin archivos, jamás",
    privacy_history_desc: "El servidor de retransmisión no conserva el contenido. Las salas vacías se eliminan inmediatamente de la memoria.",
    docs_eyebrow: "Cómo funciona",
    docs_title: "El ciclo de vida de una sala imposible de rastrear.",
    docs_desc: "Una visión precisa para usuarios, socios y revisores que desean comprender el funcionamiento técnico sin exageraciones de marketing.",
    doc_start_title: "1. Generar una Sala Fantasma",
    doc_start_desc: "El nombre de una sala crea un espacio temporal y volátil de coordinación. No existe vinculación de identidad ni creación de cuentas.",
    doc_signal_title: "2. Señalización Segura",
    doc_signal_desc: "El servidor de retransmisión dirige ofertas, respuestas y candidatos ICE cifrados de WebRTC únicamente a los pares previstos.",
    doc_chat_title: "3. Intercambio Directo en Malla",
    doc_chat_desc: "Los mensajes y el contenido enriquecido se envían a través de canales de datos peer-to-peer, evitando por completo la infraestructura del servidor de retransmisión.",
    doc_media_title: "4. Multimedia Bajo Demanda",
    doc_media_desc: "La cámara, el micrófono y la compartición de pantalla son opcionales y se renegocian dinámicamente dentro de la red cifrada.",
    doc_limit_title: "5. Límites de Escalado Intencionados",
    doc_limit_desc: "Las salas están limitadas a cinco participantes para garantizar una red en malla estable y de alto ancho de banda en dispositivos móviles y de escritorio.",
    doc_panel_title: "6. Audita tu Sesión",
    doc_panel_desc: "El panel de transparencia registra el estado técnico exacto de tus conexiones, dándote un control total sobre tu auditoría de privacidad.",
    compat_eyebrow: "Compatibilidad",
    compat_title: "Seguridad nativa del navegador en cualquier dispositivo.",
    compat_desc: "Como RoomOff se niega a ser una aplicación descargable, aprovecha los entornos seguros de aislamiento de los navegadores modernos. No existen binarios locales que puedan explotarse.",
    faq_eyebrow: "Preguntas Frecuentes",
    faq_title: "Preguntas que la gente hace antes de entrar en una sala segura.",
    faq_store_q: "Si no creo una cuenta, ¿cómo evitan los abusos?",
    faq_store_a: "Las salas son efímeras y tienen un tamaño estrictamente limitado. Sin identidades persistentes ni datos almacenados, no existe un objetivo para los atacantes. El abuso requiere dejar huellas; RoomOff no deja ninguna.",
    faq_video_q: "¿Los grabadores de pantalla o el software espía de mi PC pueden leer mis mensajes?",
    faq_video_a: "RoomOff can mask sensitive messages, warn before screen sharing, avoid key persistence, and zeroize byte buffers it controls. No browser app can guarantee protection from malware or a recorder already running on your device.",
    faq_limit_q: "¿Por qué limitar las salas a cinco participantes si son peer-to-peer?",
    faq_limit_a: "Una red en malla WebRTC implica que cada usuario se conecta directamente con todos los demás. Limitarla a cinco garantiza que el cifrado y la transmisión multimedia sigan siendo rápidos y perfectos, sin necesidad de servidores centralizados que comprometan la privacidad.",
    faq_server_q: "¿Qué ve exactamente el servidor mínimo de retransmisión?",
    faq_server_a: "Solo ve coordenadas temporales de la sala y paquetes anónimos de negociación WebRTC. Actúa como un cartero ciego. No puede leer los mensajes, ver el video ni descifrar el audio que circula entre los participantes.",
    faq_mobile_q: "¿Es realmente gratis y sin funciones premium ocultas?",
    faq_mobile_a: "Sí. La privacidad es un derecho fundamental, no una función premium destinada a generar ingresos. No existen cuentas para vender mejoras, ni costes de almacenamiento en la nube que trasladar, ni anuncios que rastreen tu comportamiento.",
    footer_prefix: "RoomOff. Salas privadas que existen únicamente mientras las personas las utilizan.",
    footer_contact: "Contáctanos",
    footer_partners: "Socios e Invitados"
  },
  it: {
    status_badge: "MODALITÀ FANTASMA ATTIVA",
    hero_title_a: "Non tracciabile.",
    hero_title_b: "Privacy di livello militare.",
    subtitle_a: "RoomOff è un ambiente WebRTC puro peer-to-peer. Le tue conversazioni, audio e video non passano mai dai nostri server. Esistono solo nella memoria effimera dei dispositivi coinvolti.",
    subtitle_b: "A differenza delle app di messaggistica tradizionali che introducono vulnerabilità sul tuo dispositivo, RoomOff non lascia alcuna traccia. Nessun eseguibile scaricato significa nessun bersaglio per malware.",
    subtitle_c: "Perché la privacy non dovrebbe mai richiedere un abbonamento, un numero di telefono o un indirizzo email.",
    cta_button: "Entra in una stanza sicura (mYRC v2.6.0-beta)",
    cta_note: "100% gratuito. Nessun account richiesto. Accesso anonimo immediato.",
    metric_no_account_value: "Zero account",
    metric_no_account_label: "Nessuna email, nessun numero di telefono, nessuna identità",
    metric_no_payment_value: "100% gratuito",
    metric_no_payment_label: "Nessun abbonamento, nessun livello premium, nessuna pubblicità",
    metric_no_storage_value: "Zero archiviazione",
    metric_no_storage_label: "Nessun database cloud, nessuna cronologia lato server",
    metric_no_download_value: "Nessuna installazione",
    metric_no_download_label: "Nativo del browser, superficie d'attacco su disco pari a zero",
    metric_peers_value: "Fino a 5 peer",
    metric_peers_label: "Mesh WebRTC per piccole stanze",
    metric_media_value: "Testo + audio + video",
    metric_media_label: "Chat ricca, camera e schermo",
    features_eyebrow: "Architettura di sicurezza di nuova generazione",
    features_title: "Costruito per un mondo in cui il tuo dispositivo potrebbe essere già compromesso.",
    features_desc: "RoomOff adds application-layer text encryption on top of browser WebRTC transport, uses volatile room keys, and clearly marks which protections are browser-enforced and which are best-effort interface defenses.",
    card_ratchet_title: "Chiavi di crittografia evolutive",
    card_ratchet_desc: "Text messages use volatile room keys, ephemeral peer handshakes and per-message ratcheting before they enter the WebRTC data channel. Browser media remains protected by WebRTC DTLS/SRTP.",
    card_ram_title: "Azzeramento della RAM",
    card_ram_desc: "RoomOff avoids key persistence, zeroizes byte buffers it controls, and minimizes how long sensitive text stays rendered. Browser internals may still keep temporary copies outside app control.",
    card_anti_capture_title: "Protezione da cattura schermo",
    card_anti_capture_desc: "I messaggi altamente sensibili possono essere configurati per essere visibili solo mentre l’utente mantiene una pressione attiva. Rilasciando il pulsante, il testo scompare immediatamente dallo schermo e dalla memoria.",
    card_immunity_title: "Immunità dell’ambiente",
    card_immunity_desc: "RoomOff adds best-effort warnings for screen sharing and suspicious debugging pauses. Browsers cannot reliably identify every recorder or remote access tool.",
    card_p2p_title: "Puro peer-to-peer",
    card_p2p_desc: "Il nostro relay si limita a mettere in contatto i browser. Una volta connessi, testo, audio e video fluiscono direttamente tra i dispositivi tramite WebRTC cifrato, bypassando completamente qualsiasi server centrale.",
    card_room_title: "Stanze autodistruggenti",
    card_room_desc: "Un URL crea un ambiente isolato. Quando l’ultima persona esce, la stanza viene eliminata dal file temporaneo del relay. È come se la conversazione non fosse mai esistita.",
    card_identity_title: "Nessun livello identità",
    card_identity_desc: "Nessuna registrazione, nessun username, nessun identificatore persistente.",
    card_ephemeral_title: "Stanze effimere",
    card_ephemeral_desc: "Spazi temporanei che possono sparire quando i peer escono.",
    card_identity_title: "Keine Identitätsschicht",
    card_identity_desc: "Keine Registrierung, keine Benutzernamen, keine dauerhaften Kennungen.",
    card_ephemeral_title: "Flüchtige Räume",
    card_ephemeral_desc: "Temporäre Koordinationsräume, die verschwinden können, wenn Peers gehen.",
    privacy_eyebrow: "Trasparenza radicale",
    privacy_title: "Vedi esattamente cosa è nascosto e da chi.",
    privacy_desc: "Non ti chiediamo di fidarti alla cieca. RoomOff offre un pannello di trasparenza nella stanza che separa ciò che vede il relay minimo da ciò che viaggia direttamente e in modo segreto tra te e i tuoi peer.",
    privacy_server_title: "Dati visibili al relay",
    privacy_server_desc: "Stato temporaneo della stanza, ID anonimi dei peer e pacchetti di handshake WebRTC. Nient’altro.",
    privacy_peer_title: "Dati trasportati dai peer",
    privacy_peer_desc: "Testo, media, audio e video cifrati end-to-end tramite canali dati WebRTC.",
    privacy_history_title: "Nessun archivio, mai",
    privacy_history_desc: "Il relay è senza stato rispetto ai contenuti. Le stanze vuote vengono eliminate immediatamente dalla memoria.",
    docs_eyebrow: "Come funziona",
    docs_title: "Il ciclo di vita di una stanza non tracciabile.",
    docs_desc: "Una panoramica precisa per utenti, partner e revisori che vogliono comprendere il flusso tecnico senza marketing.",
    doc_start_title: "1. Genera una stanza fantasma",
    doc_start_desc: "Un nome di stanza crea uno spazio di coordinamento temporaneo e volatile. Nessun legame d’identità o creazione di account.",
    doc_signal_title: "2. Segnalazione sicura",
    doc_signal_desc: "Il relay instrada offerte, risposte e candidati ICE WebRTC crittografati esclusivamente ai peer previsti.",
    doc_chat_title: "3. Scambio mesh diretto",
    doc_chat_desc: "Messaggi e contenuti avanzati vengono inviati tramite canali dati peer-to-peer, bypassando completamente l’infrastruttura del relay.",
    doc_media_title: "4. Media su richiesta",
    doc_media_desc: "Camera, microfono e condivisione schermo sono opzionali e vengono rinegoziati dinamicamente nella rete cifrata.",
    doc_limit_title: "5. Limiti di scalabilità intenzionali",
    doc_limit_desc: "Le stanze sono limitate a cinque partecipanti per garantire una rete mesh stabile e ad alta larghezza di banda su dispositivi mobili e desktop.",
    doc_panel_title: "6. Verifica la tua sessione",
    doc_panel_desc: "Il pannello di trasparenza registra lo stato tecnico esatto delle tue connessioni, dandoti controllo totale sulla tua audit di privacy.",
    compat_eyebrow: "Compatibilità",
    compat_title: "Sicurezza nativa del browser su qualsiasi dispositivo.",
    compat_desc: "Poiché RoomOff rifiuta di essere un’app scaricabile, si basa sugli ambienti sandbox rinforzati dei browser moderni. Nessun binario locale da sfruttare.",
    faq_eyebrow: "FAQ",
    faq_title: "Domande che le persone fanno prima di entrare in una stanza sicura.",
    faq_store_q: "Se non creo un account, come prevenite gli abusi?",
    faq_store_a: "Le stanze sono effimere e rigorosamente limitate nelle dimensioni. Senza identità persistenti o dati memorizzati, non esiste un bersaglio per gli attaccanti. L’abuso richiede una traccia; RoomOff non ne lascia.",
    faq_video_q: "I registratori dello schermo o lo spyware sul mio PC possono leggere i miei messaggi?",
    faq_video_a: "RoomOff can mask sensitive messages, warn before screen sharing, avoid key persistence, and zeroize byte buffers it controls. No browser app can guarantee protection from malware or a recorder already running on your device.",
    faq_limit_q: "Perché limitare le stanze a cinque peer se è peer-to-peer?",
    faq_limit_a: "Una rete mesh WebRTC significa che ogni utente si connette direttamente a tutti gli altri. Il limite a cinque garantisce che cifratura e routing multimediale restino perfetti e veloci senza server centralizzati che compromettano la privacy.",
    faq_server_q: "Cosa vede esattamente il relay minimo?",
    faq_server_a: "Vede solo coordinate temporanee della stanza e pacchetti anonimi di handshake WebRTC. Agisce come un postino cieco. Non può leggere messaggi, vedere video o decifrare audio tra peer.",
    faq_mobile_q: "È davvero gratuito senza livelli premium nascosti?",
    faq_mobile_a: "Sì. La privacy è un diritto fondamentale, non una funzione premium da monetizzare. Nessun account da vendere, nessun costo cloud da trasferire e nessuna pubblicità di tracciamento.",
    footer_prefix: "RoomOff. Stanze private che esistono solo mentre le persone le usano.",
    footer_contact: "Contattaci",
    footer_partners: "Partner e ospiti invitati"
  },
  de: {
    status_badge: "GHOST-MODUS AKTIV",
    hero_title_a: "Nicht zurückverfolgbar.",
    hero_title_b: "Datenschutz auf Militärniveau.",
    subtitle_a: "RoomOff ist eine reine WebRTC Peer-to-Peer-Umgebung. Deine Gespräche, Audio- und Videodaten laufen niemals über unsere Server. Sie existieren nur im flüchtigen Speicher der beteiligten Geräte.",
    subtitle_b: "Im Gegensatz zu klassischen Messenger-Apps, die Schwachstellen auf deinem Gerät installieren, hinterlässt RoomOff keine Spuren. Kein herunterladbares ausführbares Programm bedeutet kein Angriffsvektor für Malware.",
    subtitle_c: "Weil Datenschutz niemals ein Abonnement, eine Telefonnummer oder eine E-Mail-Adresse erfordern sollte.",
    cta_button: "Sicheren Raum betreten (mYRC v2.6.0-beta)",
    cta_note: "100% kostenlos. Kein Konto erforderlich. Sofortiger anonymer Zugriff.",
    metric_no_account_value: "Null Konten",
    metric_no_account_label: "Keine E-Mail, keine Telefonnummer, keine Identität",
    metric_no_payment_value: "100% kostenlos",
    metric_no_payment_label: "Keine Abos, keine Premium-Stufen, keine Werbung",
    metric_no_storage_value: "Null Speicherung",
    metric_no_storage_label: "Keine Cloud-Datenbank, kein serverseitiger Verlauf",
    metric_no_download_value: "Keine Installation",
    metric_no_download_label: "Browser-nativ, keine Angriffsfläche auf der Festplatte",
    metric_peers_value: "Bis zu 5 Peers",
    metric_peers_label: "WebRTC-Mesh für kleine Räume",
    metric_media_value: "Text + Audio + Video",
    metric_media_label: "Rich Chat, Kamera und Bildschirm",
    features_eyebrow: "Sicherheitsarchitektur der nächsten Generation",
    features_title: "Gebaut für eine Welt, in der dein Gerät bereits kompromittiert sein könnte.",
    features_desc: "RoomOff adds application-layer text encryption on top of browser WebRTC transport, uses volatile room keys, and clearly marks which protections are browser-enforced and which are best-effort interface defenses.",
    card_ratchet_title: "Dynamische Verschlüsselungsschlüssel",
    card_ratchet_desc: "Verwendet die Double-Ratchet-Architektur. Jede Nachricht und jedes Medienpaket nutzt einen anderen Schlüssel. Wenn ein Schlüssel kompromittiert wird, ist nur dieser eine Millisekunden-Datenpunkt betroffen. Vergangenheit und Zukunft bleiben geschützt.",
    card_ram_title: "RAM-Nullisierung",
    card_ram_desc: "RoomOff avoids key persistence, zeroizes byte buffers it controls, and minimizes how long sensitive text stays rendered. Browser internals may still keep temporary copies outside app control.",
    card_anti_capture_title: "Anti-Screen-Capture",
    card_anti_capture_desc: "Hochsensible Nachrichten können so konfiguriert werden, dass sie nur sichtbar sind, solange der Nutzer aktiv gedrückt hält. Lässt er los, verschwindet der Text sofort aus Bildschirm und Speicher.",
    card_immunity_title: "Umgebungs-Überwachung",
    card_immunity_desc: "RoomOff adds best-effort warnings for screen sharing and suspicious debugging pauses. Browsers cannot reliably identify every recorder or remote access tool.",
    card_p2p_title: "Reines Peer-to-Peer",
    card_p2p_desc: "Unser Relay verbindet nur Browser miteinander. Sobald verbunden, fließen Text, Audio und Video direkt zwischen den Geräten über verschlüsseltes WebRTC, vollständig ohne zentralen Server.",
    card_room_title: "Selbstzerstörende Räume",
    card_room_desc: "Eine URL erzeugt eine isolierte Umgebung. Wenn die letzte Person den Raum verlässt, wird er aus der temporären Relay-Datei gelöscht. Es ist, als hätte die Konversation nie existiert.",
    card_identity_title: "Sem camada de identidade",
    card_identity_desc: "Sem cadastro, sem nomes de usuário, sem identificadores persistentes.",
    card_ephemeral_title: "Salas efêmeras",
    card_ephemeral_desc: "Espaços temporários que podem desaparecer quando os peers saem.",
    privacy_eyebrow: "Radikale Transparenz",
    privacy_title: "Sieh genau, was verborgen ist und vor wem.",
    privacy_desc: "Wir verlangen kein blindes Vertrauen. RoomOff bietet ein Transparenz-Panel im Raum, das trennt, was das minimale Relay sieht, und was direkt und geheim zwischen dir und deinen Peers übertragen wird.",
    privacy_server_title: "Vom Relay sichtbare Daten",
    privacy_server_desc: "Temporärer Raumstatus, anonyme Peer-IDs und WebRTC-Handshake-Pakete. Mehr nicht.",
    privacy_peer_title: "Peer-getragene Daten",
    privacy_peer_desc: "Text, Medien, Audio und Video Ende-zu-Ende verschlüsselt über WebRTC-Datenkanäle.",
    privacy_history_title: "Keine Speicherung, niemals",
    privacy_history_desc: "Das Relay ist zustandslos in Bezug auf Inhalte. Leere Räume werden sofort aus dem Speicher gelöscht.",
    docs_eyebrow: "So funktioniert es",
    docs_title: "Der Lebenszyklus eines nicht nachverfolgbaren Raums.",
    docs_desc: "Eine präzise Übersicht für Nutzer, Partner und Prüfer, die den technischen Ablauf ohne Marketing verstehen wollen.",
    doc_start_title: "1. Ghost-Raum erstellen",
    doc_start_desc: "Ein Raumname erzeugt einen temporären, flüchtigen Koordinationsraum. Keine Identität und kein Konto erforderlich.",
    doc_signal_title: "2. Sichere Signalisierung",
    doc_signal_desc: "Das Relay leitet verschlüsselte WebRTC Offers, Answers und ICE-Kandidaten ausschließlich an die vorgesehenen Peers weiter.",
    doc_chat_title: "3. Direkter Mesh-Austausch",
    doc_chat_desc: "Nachrichten und Rich Content werden über Peer-to-Peer-Datenkanäle übertragen und umgehen vollständig die Relay-Infrastruktur.",
    doc_media_title: "4. Medien auf Abruf",
    doc_media_desc: "Kamera, Mikrofon und Bildschirmfreigabe sind optional und werden dynamisch über das verschlüsselte Mesh neu ausgehandelt.",
    doc_limit_title: "5. Bewusste Skalierungsgrenzen",
    doc_limit_desc: "Räume sind auf fünf Teilnehmer begrenzt, um ein stabiles, hochperformantes Mesh-Netzwerk auf Mobil- und Desktopgeräten zu gewährleisten.",
    doc_panel_title: "6. Sitzung prüfen",
    doc_panel_desc: "Das Transparenz-Panel protokolliert den technischen Zustand deiner Verbindungen und gibt dir volle Kontrolle über deine Datenschutzprüfung.",
    compat_eyebrow: "Kompatibilität",
    compat_title: "Native Browsersicherheit auf jedem Gerät.",
    compat_desc: "Da RoomOff keine installierbare Anwendung ist, nutzt es die gehärteten Sandbox-Umgebungen moderner Browser. Keine lokalen Binärdateien als Angriffsfläche.",
    faq_eyebrow: "FAQ",
    faq_title: "Fragen, die Menschen vor dem Betreten eines sicheren Raums stellen.",
    faq_store_q: "Wenn ich kein Konto erstelle, wie verhindert ihr Missbrauch?",
    faq_store_a: "Räume sind flüchtig und strikt in der Größe begrenzt. Ohne persistente Identitäten oder gespeicherte Daten gibt es kein Ziel für Angreifer. Missbrauch benötigt eine Spur, RoomOff hat keine.",
    faq_video_q: "Können Screen Recorder oder Spyware auf meinem PC meine Nachrichten lesen?",
    faq_video_a: "Standard-Spyware hat Schwierigkeiten mit RoomOff. Unsere RAM-Nullisierung löscht entschlüsselte Daten in Millisekunden, und Anti-Capture-Modi verhindern, dass sensible Inhalte lange genug sichtbar bleiben, um aufgezeichnet zu werden.",
    faq_limit_q: "Warum sind Räume auf fünf Teilnehmer begrenzt, wenn es Peer-to-Peer ist?",
    faq_limit_a: "Ein WebRTC-Mesh bedeutet, dass jeder Nutzer direkt mit allen anderen verbunden ist. Die Begrenzung auf fünf stellt sicher, dass Verschlüsselung und Medienrouting stabil und schnell bleiben, ohne zentrale Server.",
    faq_server_q: "Was sieht das minimale Relay genau?",
    faq_server_a: "Es sieht nur temporäre Raumkoordinaten und anonyme WebRTC-Handshake-Pakete. Es fungiert wie ein blinder Postbote. Es kann keine Nachrichten lesen, keine Videos sehen und kein Audio entschlüsseln.",
    faq_mobile_q: "Ist es wirklich kostenlos ohne versteckte Premium-Stufen?",
    faq_mobile_a: "Ja. Datenschutz ist ein Grundrecht und keine Premiumfunktion. Keine Konten zum Verkaufen, keine Cloud-Kosten und keine Werbung zur Verhaltensverfolgung.",
    footer_prefix: "RoomOff. Private Räume, die nur existieren, solange Menschen sie nutzen.",
    footer_contact: "Kontakt",
    footer_partners: "Partner und eingeladene Gäste"
  },
  pt: {
    status_badge: "MODO FANTASMA ATIVO",
    hero_title_a: "Não rastreável.",
    hero_title_b: "Privacidade de nível militar.",
    subtitle_a: "RoomOff é um ambiente WebRTC puro peer-to-peer. As suas conversas, áudio e vídeo nunca passam pelos nossos servidores. Existem apenas na memória efêmera dos dispositivos envolvidos.",
    subtitle_b: "Ao contrário de aplicações de mensagens tradicionais que instalam vulnerabilidades no seu dispositivo, o RoomOff não deixa rastros. Sem executáveis descarregados significa nenhum alvo para malware.",
    subtitle_c: "Porque a privacidade nunca deveria exigir uma assinatura, um número de telefone ou um endereço de email.",
    cta_button: "Entrar numa Sala Segura (mYRC v2.6.0-beta)",
    cta_note: "100% gratuito. Não é necessário conta. Acesso anônimo instantâneo.",
    metric_no_account_value: "Zero Contas",
    metric_no_account_label: "Sem email, sem número de telefone, sem identidade",
    metric_no_payment_value: "100% gratuito",
    metric_no_payment_label: "Sem assinaturas, sem níveis premium, sem anúncios",
    metric_no_storage_value: "Zero Armazenamento",
    metric_no_storage_label: "Sem base de dados na nuvem, sem histórico no servidor",
    metric_no_download_value: "Sem Instalação",
    metric_no_download_label: "Nativo do navegador, superfície de ataque no disco zero",
    metric_peers_value: "Até 5 peers",
    metric_peers_label: "Malha WebRTC para salas pequenas",
    metric_media_value: "Texto + áudio + vídeo",
    metric_media_label: "Chat rico, câmera e tela",
    features_eyebrow: "Arquitetura de Segurança de Próxima Geração",
    features_title: "Construído para um mundo onde o seu dispositivo pode já estar comprometido.",
    features_desc: "RoomOff adds application-layer text encryption on top of browser WebRTC transport, uses volatile room keys, and clearly marks which protections are browser-enforced and which are best-effort interface defenses.",
    card_ratchet_title: "Chaves de Encriptação Evolutivas",
    card_ratchet_desc: "Text messages use volatile room keys, ephemeral peer handshakes and per-message ratcheting before they enter the WebRTC data channel. Browser media remains protected by WebRTC DTLS/SRTP.",
    card_ram_title: "Zeragem de RAM",
    card_ram_desc: "Os dados desencriptados existem na RAM do dispositivo apenas durante alguns milissegundos antes de serem agressivamente sobrescritos. Spyware que analise a memória encontrará apenas zeros vazios, não as suas conversas.",
    card_anti_capture_title: "Proteção contra Captura de Ecrã",
    card_anti_capture_desc: "Mensagens altamente sensíveis podem ser configuradas para só serem visíveis enquanto o utilizador mantém pressão ativa. Ao soltar, o texto desaparece imediatamente do ecrã e da memória.",
    card_immunity_title: "Imunidade do Ambiente",
    card_immunity_desc: "RoomOff adds best-effort warnings for screen sharing and suspicious debugging pauses. Browsers cannot reliably identify every recorder or remote access tool.",
    card_p2p_title: "Puro Peer-to-Peer",
    card_p2p_desc: "O nosso relay apenas liga navegadores entre si. Uma vez conectados, texto, áudio e vídeo fluem diretamente entre dispositivos via WebRTC encriptado, sem qualquer servidor central.",
    card_room_title: "Salas Autodestrutivas",
    card_room_desc: "Um URL cria um ambiente isolado. Quando a última pessoa sai, a sala é apagada do ficheiro temporário do relay. É como se a conversa nunca tivesse existido.",
    privacy_eyebrow: "Transparência Radical",
    privacy_title: "Veja exatamente o que está oculto e de quem.",
    privacy_desc: "Não pedimos confiança cega. O RoomOff fornece um painel de transparência dentro da sala que separa o que o relay mínimo vê do que viaja diretamente e em segredo entre si e os seus pares.",
    privacy_server_title: "Dados visíveis para o relay",
    privacy_server_desc: "Estado temporário da sala, IDs anónimos de pares e pacotes de handshake WebRTC. Nada mais.",
    privacy_peer_title: "Dados transportados pelos pares",
    privacy_peer_desc: "Texto, media, áudio e vídeo encriptados de ponta a ponta através de canais de dados WebRTC.",
    privacy_history_title: "Sem arquivo, nunca",
    privacy_history_desc: "O relay não mantém estado sobre conteúdo. Salas vazias são imediatamente apagadas da memória.",
    docs_eyebrow: "Como funciona",
    docs_title: "O ciclo de vida de uma sala não rastreável.",
    docs_desc: "Uma visão precisa para utilizadores, parceiros e revisores que querem compreender o fluxo técnico sem marketing.",
    doc_start_title: "1. Gerar uma Sala Fantasma",
    doc_start_desc: "Um nome de sala cria um espaço de coordenação temporário e volátil. Sem ligação de identidade ou criação de conta.",
    doc_signal_title: "2. Sinalização Segura",
    doc_signal_desc: "O relay encaminha ofertas, respostas e candidatos ICE WebRTC encriptados apenas para os pares pretendidos.",
    doc_chat_title: "3. Troca Direta em Malha",
    doc_chat_desc: "Mensagens e conteúdo avançado são enviados através de canais de dados peer-to-peer, contornando completamente a infraestrutura do relay.",
    doc_media_title: "4. Media sob Demanda",
    doc_media_desc: "Câmara, microfone e partilha de ecrã são opcionais e renegociados dinamicamente na malha encriptada.",
    doc_limit_title: "5. Limites de Escala Intencionais",
    doc_limit_desc: "As salas são limitadas a cinco participantes para garantir uma rede em malha estável e de alta largura de banda em dispositivos móveis e desktop.",
    doc_panel_title: "6. Auditar a Sessão",
    doc_panel_desc: "O painel de transparência regista o estado técnico exato das suas ligações, dando controlo total sobre a auditoria de privacidade.",
    compat_eyebrow: "Compatibilidade",
    compat_title: "Segurança nativa do navegador em qualquer dispositivo.",
    compat_desc: "Como o RoomOff recusa ser uma aplicação instalável, depende dos ambientes sandbox reforçados dos navegadores modernos. Sem binários locais para explorar.",
    faq_eyebrow: "FAQ",
    faq_title: "Perguntas que as pessoas fazem antes de entrar numa sala segura.",
    faq_store_q: "Se não criar uma conta, como evitam abusos?",
    faq_store_a: "As salas são efémeras e estritamente limitadas em tamanho. Sem identidades persistentes ou dados armazenados, não existe alvo para atacantes. Abuso requer rastos; o RoomOff não deixa nenhum.",
    faq_video_q: "Os gravadores de ecrã ou spyware no meu PC podem ler as minhas mensagens?",
    faq_video_a: "Spyware padrão tem dificuldades contra o RoomOff. A nossa zeragem de RAM apaga dados desencriptados em milissegundos e os modos anti-captura impedem que informação sensível permaneça no ecrã tempo suficiente para ser registada.",
    faq_limit_q: "Por que limitar salas a cinco participantes se é peer-to-peer?",
    faq_limit_a: "Uma malha WebRTC significa que cada utilizador liga-se diretamente a todos os outros. O limite de cinco garante que encriptação e encaminhamento de media permanecem estáveis e rápidos sem servidores centrais.",
    faq_server_q: "O que exatamente o relay mínimo vê?",
    faq_server_a: "Vê apenas coordenadas temporárias da sala e pacotes anónimos de handshake WebRTC. Atua como um carteiro cego. Não pode ler mensagens, ver vídeo ou descodificar áudio entre pares.",
    faq_mobile_q: "É realmente gratuito sem níveis premium ocultos?",
    faq_mobile_a: "Sim. Privacidade é um direito fundamental, não uma funcionalidade premium. Sem contas para vender, sem custos de cloud e sem anúncios de rastreamento comportamental.",
    footer_prefix: "RoomOff. Salas privadas que só existem enquanto são usadas.",
    footer_contact: "Contacte-nos",
    footer_partners: "Parceiros e convidados"
  }
};

const supported = ["en", "fr", "es", "it", "de", "pt"];
const securityTruthKeys = [
  "features_desc",
  "card_ratchet_desc",
  "card_ram_desc",
  "card_immunity_desc",
  "faq_video_a",
  "doc_commands_title",
  "doc_commands_desc",
  "doc_commands_link"
];

function applyTranslations(lang) {
  const dict = translations[lang] || translations.en;

  document.querySelectorAll("[translate]").forEach((el) => {
    const key = el.getAttribute("translate");
    if (dict[key] !== undefined || translations.en[key] !== undefined) {
      el.innerText = securityTruthKeys.includes(key) ? translations.en[key] : dict[key] || translations.en[key];
    }
  });
}

function initLanguageSystem(lang) {
  applyTranslations(lang);
}

function setLangCookie(lang) {
  document.cookie = "lang=" + lang + "; path=/; max-age=" + 365 * 24 * 60 * 60;
}

function goToLang(lang) {
  const parts = window.location.pathname.split("/").filter(Boolean);

  if (supported.includes(parts[0])) {
    parts.shift();
  }

  let newPath = parts.length ? "/" + parts.join("/") + "/" : "/";

  if (lang !== "en") {
    newPath = "/" + lang + newPath;
  }

  window.location.href = newPath;
}

document.addEventListener("DOMContentLoaded", () => {
  const select = document.getElementById("langSelect");
  if (!select) return;

  const currentLang = window.APP_LANG || "en";
  select.value = currentLang;
  applyTranslations(currentLang);

  select.addEventListener("change", (event) => {
    const lang = event.target.value;
    setLangCookie(lang);
    applyTranslations(lang);
    goToLang(lang);
  });
});
